### ISSUE TITLE
Typescript config

### ISSUE THREAD

**Issue by Elsoberanold** [mgcrea/fastify-session#23]
Hi! Currently I am trying to implement this library to set a session based auth. However, I am struggling with the following error... What TSconfigs should I use?

`{"level":50,"time":1676542402897,"pid":15040,"hostname”:”PC”,”err": { "type": "Error", "message":"require() of ES Module server/node_modules/nanoid/index.js from server/node_modules/@mgcrea/fastify-session/dist/index.cjs not supported. Instead change the require of index.js in server/node_modules/@mgcrea/fastify-session/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.", "stack":"Error [ERR_REQUIRE_ESM]: require() of ES Module server/node_modules/nanoid/index.js from server/node_modules/@mgcrea/fastify-session/dist/index.cjs not supported.Instead change the require of index.js in server/node_modules/@mgcrea/fastify-session/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.\n    at require.extensions..jsx.require.extensions..js (/private/var/folders/17/syph5qn950scym0mh4fjg_9m0000gn/T/ts-node-dev-hook-847473055250209.js:114:20)\n    at Object.nodeDevHook [as .js] (server/node_modules/ts-node-dev/lib/hook.js:63:13)\n    at Object.<anonymous> (server/node_modules/@mgcrea/fastify-session/dist/index.cjs:121:21)\n    at Module._compile (server/node_modules/source-map-support/source-map-support.js:568:25)\n    at require.extensions..jsx.require.extensions..js (/private/var/folders/17/syph5qn950scym0mh4fjg_9m0000gn/T/ts-node-dev-hook-847473055250209.js:114:20)\n    at Object.nodeDevHook [as .js] (server/node_modules/ts-node-dev/lib/hook.js:63:13)\n    at Object.<anonymous> (server/src/plugins/setup-auth.ts:9:43)\n    at Module._compile (server/node_modules/source-map-support/source-map-support.js:568:25)\n    at m._compile (/private/var/folders/17/syph5qn950scym0mh4fjg_9m0000gn/T/ts-node-dev-hook-847473055250209.js:69:33)\n    at require.extensions..jsx.require.extensions..js (/private/var/folders/17/syph5qn950scym0mh4fjg_9m0000gn/T/ts-node-dev-hook-847473055250209.js:114:20)\n    at require.extensions.<computed> (/private/var/folders/17/syph5qn950scym0mh4fjg_9m0000gn/T/ts-node-dev-hook-847473055250209.js:71:20)\n    at Object.nodeDevHook [as .ts] (server/node_modules/ts-node-dev/lib/hook.js:63:13)\n    at loadPlugin (server/node_modules/@fastify/autoload/index.js:259:15)\n    at server/node_modules/@fastify/autoload/index.js:43:12\n    at Array.map (<anonymous>)\n    at autoload (server/node_modules/@fastify/autoload/index.js:42:33)","code":"ERR_REQUIRE_ESM"},"msg":"require() of ES Module server/node_modules/nanoid/index.js from server/node_modules/@mgcrea/fastify-session/dist/index.cjs not supported.\nInstead change the require of index.js in server/node_modules/@mgcrea/fastify-session/dist/index.cjs to a dynamic import() which is available in all CommonJS modules."}`

Here is my tsconfig file

```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true,
    "useDefineForClassFields": true,
    "allowJs": false,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "declaration": true,
    "rootDir": "./src",
    "outDir": "./build",
    "baseUrl": "./"
  },
  "include": ["src"],
}
```

**Comment by mgcrea** [comment]
Unfortunately it does look like the latest version of `nanoid` dropped support for non-esm projects. I reverted back to the last version with CJS support and released a new version `1.1.0`, should work now.
